#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Attempt to unload modules, fail silently if not possible
        echo "Unload modules if possible"
        rmmod tuxedo_io > /dev/null 2>&1 || true
        rmmod uniwill_wmi > /dev/null 2>&1 || true
        rmmod clevo_wmi > /dev/null 2>&1 || true
        rmmod clevo_acpi > /dev/null 2>&1 || true
        rmmod tuxedo_keyboard > /dev/null 2>&1 || true
        rmmod ite_8291 > /dev/null 2>&1 || true
        rmmod ite_8291_lb > /dev/null 2>&1 || true
        rmmod ite_8297 > /dev/null 2>&1 || true
        rmmod ite_829x > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_keyboard > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_sensors > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_power_profiles > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_ec > /dev/null 2>&1 || true
        rmmod tuxedo_compatibility_check > /dev/null 2>&1 || true
    ;;
esac

#DEBHELPER#

