#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Attempt to unload modules, fail silently if not possible

        # Stop UPower as it does not handle well when kbd_backlight entries disapear
        echo "Stop UPower temporarily"
        systemctl stop upower 2>&1 || true

        echo "Unload modules if possible"
        rmmod tuxedo_nb02_nvidia_power_ctrl > /dev/null 2>&1 || true
        rmmod tuxedo_io > /dev/null 2>&1 || true
        rmmod uniwill_wmi > /dev/null 2>&1 || true
        rmmod clevo_wmi > /dev/null 2>&1 || true
        rmmod clevo_acpi > /dev/null 2>&1 || true
        rmmod tuxedo_keyboard > /dev/null 2>&1 || true
        rmmod ite_8291 > /dev/null 2>&1 || true
        rmmod ite_8291_lb > /dev/null 2>&1 || true
        rmmod ite_8297 > /dev/null 2>&1 || true
        rmmod ite_829x > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_fan_control > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_kbd_backlight > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_keyboard > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_sensors > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_power_profiles > /dev/null 2>&1 || true
        rmmod tuxedo_nb05_ec > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_kbd_backlight > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_power_profiles > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_sensors > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_keyboard > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_wmi_ab > /dev/null 2>&1 || true
        rmmod tuxedo_nb04_wmi_bs > /dev/null 2>&1 || true
        rmmod tuxedo_compatibility_check > /dev/null 2>&1 || true
        rmmod stk8321 > /dev/null 2>&1 || true
        rmmod gxtp7380 > /dev/null 2>&1 || true
        rmmod tuxedo_tuxi_fan_control > /dev/null 2>&1 || true
        rmmod tuxi_acpi > /dev/null 2>&1 || true

        # Restart UPower
        echo "Start UPower again"
        systemctl restart upower 2>&1 || true
    ;;
esac

#DEBHELPER#

