obj-m += clevo_acpi.o
obj-m += clevo_wmi.o
obj-m += tuxedo_keyboard.o
obj-m += uniwill_wmi.o

obj-y += ite_8291/
obj-y += ite_8291_lb/
obj-y += ite_8297/
obj-y += ite_829x/
obj-y += tuxedo_compatibility_check/
obj-y += tuxedo_io/
obj-y += tuxedo_nb05/
